packages/app/src/features/auth/errors.ts
packages/app/src/features/auth/service/login.ts
packages/app/src/lib/ErrorMapper.ts
packages/app/src/lib/env.ts
packages/app/src/types/Errors.ts

errorMapper를 통해 에러 메시지를 관리하는 기능 추가
- errorMapper를 통한 에러 메시지 관리 시스템 도입
- 기존 로그인 기능의 에러 메시지 띄우는 방식을 errorMapper로 변경
- errorMapper에 error 객체와 Errors 타입의 객체를 넣어주면 에러 메시지가 나오는 형태이다
- Errors 타입의 객체는 아래와 같은 형식이다
```ts
interface Errors {
[baseUrl: string]: {
[url: string]: {
[method: string]: {
[status: number]: string
'*'?: string
}
}
}
}
```
alert도 만들어야 할 듯...

[#24] 에러 관리 시스템 추가

---

packages/shared/src/atoms/Input/index.tsx
packages/shared/src/atoms/Input/style.ts

- input의 reset 기능을 활성화 또는 비활성화 할 수 있게 했습니다
- 기존 공간을 차지하던 reset button을 완전히 없애게 변경했습니다
```tsx
import { Input } from '@sms/shared'
const Component = () => {
return (
<Input isReset /> // 이렇게 하면 reset 기능이 활성화됨
)
}
```

[#60] input의 reset 기능

---

packages/shared/src/atoms/Select/index.stories.tsx
packages/shared/src/atoms/Select/index.tsx

직접 입력을 선택적으로 추가할 수 있는 기능을 추가했습니다
directInput이라는 props를 boolean 값으로 넘겨 받게 하고
directInput이 true면 직접 입력이 활성화 되도록 변경했습니다
```tsx
interface FormType {
select: string
}
const Component = () => {
const { register, handleSubmit, control } = useForm<FormType>()
const onSubmit = handleSubmit(() => {})
return (
<form onSubmit={onSubmit}>
<Select
name='select'
register={register}
options={options}
control={control}
directInput // 요고 추가함
/>
<button type='submit'>submit</button>
</form>
)
}
```

[#72] 직접 입력 선택 기능 추가

---

packages/shared/src/atoms/Select/index.stories.tsx
packages/shared/src/atoms/Select/index.tsx
packages/shared/src/atoms/Select/type.ts

label과 value 가 뒤바뀌는 문제가 발생했습니다
보여지는 부분은 label로 띄우고 처리되는 값은 value로 처리 되게 만들었습니다
storybook의 예시 값이 살짝 변경되었습니다

[#74] label가 value가 뒤바뀐 문제 해결

---

packages/app/src/features/auth/components/GuestLink.tsx
packages/app/src/features/auth/components/index.ts
packages/app/src/templates/LoginTemplate/index.tsx
packages/app/src/templates/LoginTemplate/style.ts

로그인 페이지에서 메인 페이지로 갈 수 있게 하는 기능을 추가했습니다
로그인 페이지의 반응형에 문제가 있어 수정했습니다
- `GuestLink` 컴포넌트를 추가해 메인페이지로 갈 수 있게 하는 기능을 추가했습니다
- margin으로 콘텐츠를 밀어내서 발생한 이슈를 padding으로 변경했습니다

[#77] 로그인 페이지 기능 추가 및 반응형 수정

---

packages/app/src/components/SEO/index.tsx

seo를 추가한 이후로 아래와 같은 에러가 발생해서 수정했습니다
```
Warning: A title element received an array with more than 1 element as children. In browsers title Elements can only have Text Nodes as children. If the children being rendered output more than a single text node in aggregate the browser will display markup and comments as text in the title and hydration will likely fail and fall back to client rendering
```
title 태그의 value값을 수정했습니다
[참고 자료](https://velog.io/@xmun74/A-title-element-received-an-array-with-more-than-1-element-as-children)

[#76] title 에러 픽스

---

packages/app/src/api/CustomBaseQuery.ts
packages/app/src/api/axiosApi.ts
packages/app/src/api/rtkApi.ts
packages/app/src/features/auth/service/login.ts
packages/app/src/features/auth/service/reissue.ts
packages/app/src/features/auth/type/TokenResponse.ts
packages/app/src/lib/Observable.ts
packages/app/src/lib/Token.ts
packages/app/src/lib/TokenManager.ts
packages/app/src/lib/needsTokenRefresh.ts

Cookie가 잘 동작하지 않는 관계로 Autorization에 할당하는 방법을 사용하기로 했습니다
- axios interceptor 추가
- TokenManager 추가
- Obervable 추가
- needsTokenRefresh를 만들어서 인가가 필요한 요청인지 확인
- rtk query에서 fetchBaseQuery 대신 CustomBaseQuery를 만들었음

[#91] 토큰 재발급 및 토큰 할당 로직 추가

---

packages/shared/src/atoms/Input/index.tsx
packages/shared/src/molecules/Select/index.stories.tsx
packages/shared/src/molecules/Select/index.tsx
packages/shared/src/molecules/Select/style.ts

Select 컴포넌트에는 아래와 같은 문제점 들이 있었습니다
- select에서 reset 버튼이 잘 동작하지 않습니다
- default 값이 할당 되지 않습니다
> select에서 reset 버튼이 잘 동작하지 않습니다
어쩔 수 없이 지금은 reset button을 지우기로 결졍했습니다
다음에 리팩토링을 진행 할 때 select 컴포넌트를 완전히 갈아 엎을 예정이라 그때 가서 하는 걸로
> default 값이 할당 되지 않습니다
defaultValue가 할당 되지 않아서 할당되지 않은 상태에서 시작하는 걸로 변경했습니다
때문에 error 값을 받아 필수 값이라는 걸 알리는 부분이 추가되었습니다
- input에 error를 띄우는 요소 때문에 4px 정도가 아래로 내려오는 문제를 해결했습니다

[#80] select 컴포넌트의 문제점 해결

---

packages/app/src/features/student/molecules/StudentDetail/style.ts
packages/shared/src/atoms/StudentCard/index.tsx
packages/shared/src/atoms/StudentCard/style.ts

학생 카드와 디테일의 자잘한 스타일 문제를 해결했습니다
태그가 밖으로 나오는 문제를 그냥 자르는 걸로 해결
태그들의 간격이 맞지 않는 문제 해결
닫는 버튼이 아래로 내려가는 문제 해결

[#110] 학생 카드와 학생 디테일 스타일 수정

---

packages/app/src/api/axiosApi.ts
packages/app/src/api/rtkApi.ts
packages/app/src/features/auth/hook/useLoggedIn.tsx
packages/app/src/features/auth/service/loggedInApi.ts
packages/app/src/features/student/hooks/useStudentDetail.tsx
packages/app/src/features/student/service/studentApi/index.ts
packages/app/src/lib/TokenManager.ts
packages/app/src/pages/login.tsx
packages/app/src/pages/register.tsx
packages/app/src/types/Role.d.ts

페이지별 권한 처리를 추가했습니다
- 각각의 페이지에 권한에 따라 접근 할 수 있는지 없는지를 처리했습니다
- 권한에 따라 학생 디테일 요청을 날릴 수 있게 변경했습니다
모든 권한 처리를 useLoggedIn이라는 훅에서 처리해서 나중에 쉽게 처리하는 방법을 찾아봐야 할 것 같습니다

[#111] 페이지별 권한 처리

---

packages/app/src/features/student/molecules/StudentDetail/style.ts
packages/app/src/features/student/molecules/StudentList/style.ts
packages/app/src/features/student/templates/StudentsTemplate/style.ts
packages/shared/src/atoms/StudentCard/style.ts
packages/shared/src/molecules/Header/style.ts

모바일에서 봤을 때 깨지던 디자인을 수정했습니다
- 학생 카드 반응형 수정
- 해더 반응형 수정
- 학생 임시 이미지 사이즈 수정
- 학생 카드 사이사이 border 추가

[#121] 메인 페이지 반응형 및 디자인 수정

---

packages/app/src/features/auth/errors.ts
packages/app/src/features/auth/hook/useAuth.tsx
packages/app/src/features/auth/hook/useLogout.tsx
packages/app/src/features/auth/hook/useWithdraw.tsx
packages/app/src/features/auth/service/login.ts
packages/app/src/features/auth/service/logout.ts
packages/app/src/features/auth/service/withdraw.ts
packages/app/src/features/register/hooks/useRegister.tsx
packages/app/src/features/register/services/PostFileService/index.tsx
packages/app/src/features/register/services/PostStudentInfoService/index.tsx
packages/app/src/features/student/hooks/useStudent.tsx
packages/app/src/features/student/service/studentApi/index.ts

api 요청에 toast를 띄우는 작업을 진행했습니다
- 로그인, 로그아웃, 회원탈퇴, 회원가입, 이미지 업로드 api 요청에 toast를 띄우게 만들었습니다
로그인과 로그아웃이 끝난 후에 페이지를 reload 하는 게 아니라 student 값을 다시 가져오는 방식으로 변경했습니다
백 명세서에 에러 관련된 명세가 잘 되어 있지 않아 나중에 추가해야할 것 같습니다

[#127] api 요청에 toast 띄우기

---

packages/app/src/api/axiosApi.ts
packages/app/src/features/student/hooks/useStudent.tsx
packages/app/src/features/student/service/errors.ts

가끔 요청을 하다 잘못 걸리면 무한 요청에 빠지는 경우가 생겼습니다
본의아니게 ddos공격을 하게돼서 수정을 하게 되었습니다
- axios의 response interceptor에 retry 기능을 제거하고 401에러가 발생하면 토큰을 지우도록 변경했습니다
- 학생 리스트를 요청할 때 실패를 하면 에러 toast를 띄우는 기능 추가

[#131] 무한 요청 문제 해결

---

packages/app/src/api/rtkApi.ts
packages/app/src/features/auth/hook/useLoggedIn.tsx
packages/app/src/features/auth/hook/useLogout.tsx
packages/app/src/features/auth/hook/useWithdraw.tsx
packages/app/src/features/auth/service/loggedInApi.ts
packages/app/src/features/student/hooks/useStudentDetail.tsx
packages/app/src/features/student/templates/StudentsTemplate/index.tsx
packages/app/src/pages/index.tsx
packages/app/src/pages/login.tsx
packages/app/src/pages/register.tsx

전 useLoggedIn 로직은 너무 복잡하고 확장성도 너무 낮아 수정을 진행했습니다
- useLoggedIn에서 props로 redirectTo와 redirectToIfFound받아서 처리하도록 수정했습니다
- redirectTo는 로그인이 되지 않은 상태에서 페이지에 접근하면 어디로 보낼지를 적습니다
- redirectToIfFound는 로그인이 된 상태에서 페이지 접근을 막을 때 사용합니다
- 하지만 `/register`는 예외로 isExist가 false 일때만 접근 가능하게 했습니다
- 두 props는 모두 옵셔널이어서 언제나 접근이 가능한 페이지는 아무것도 넘겨주지 않아도 됩니다
- 로그아웃 또는 회원 탈퇴를 진행한 후에도 loggedIn값이 변경되지 않아서 api 요청 이후에 refetchLoggedIn을 실행해 값을 초기화 해주었습니다

[#130] 페이지 별 권한 로직 수정

---

packages/app/src/features/auth/components/GuestLink.tsx
packages/app/src/features/register/hooks/useRegister.tsx
packages/app/src/templates/LoginTemplate/index.tsx
packages/app/src/templates/LoginTemplate/style.ts
packages/shared/src/atoms/Toast/style.ts

모바일에서 로그인 페이지에 접속하면 영상 재생도 막히고 반응형도 이상한 문제가 있었습니다
- 반응형을 위해 100vh를 사용하는 코드를 제거했습니다
- iOS 환경에서는 webm을 지원하지 않을 뿐더러 자동재생도 막힌다는 걸 알고 mp4를 추가한 후에 자동 재생 옵션을 추가했습니다
- toast style을 수정했습니다
- 회원 가입 이후 처리를 수정했습니다
절전 모드에서는 영상 자동재생이 완전히 막힙니다

[#124] 로그인 페이지 반응형 구현

---

packages/app/src/features/register/hooks/useRegister.tsx
packages/app/src/features/register/molecules/ProfileInputs/index.tsx
packages/app/src/features/register/organisms/RegisterForm/index.tsx
packages/app/src/features/register/services/PostStudentInfoService/index.tsx
packages/app/src/features/register/type/RegisterFormType.ts
packages/shared/src/molecules/SearchInput/index.stories.tsx
packages/shared/src/molecules/SearchInput/index.tsx

기존 방식은 외부로 부터 값을 받은 후에 setValue를 통해 값을 바꿔주는 방식이었는데
reset 함수가 동작 하지 않는 문제가 발생해서 watch를 통해 값을 받아서 내부에서는 이 watch 값을 통해 화면에 보여주도록 변경했다
- SearchInput 컴포넌트 수정
- SearchInput을 사용하고 있는 회원 가입쪽을 수정했다

[#154] SearchInput 메커니즘 개선

---

packages/app/src/components/Loading/style.ts
packages/app/src/components/ModalPortal/style.ts
packages/app/src/components/NotFound/style.ts
packages/app/src/features/dialog/atoms/Portal/style.ts
packages/app/src/features/student/molecules/FilterModal/style.ts
packages/app/src/features/student/molecules/StudentDetail/style.ts
packages/app/src/features/student/templates/StudentsTemplate/style.ts
packages/app/src/layouts/LoginLayout/style.ts
packages/shared/src/style/global.css

모바일에서 100vh를 사용하면 높이 값이 맞지 않는 문제가 있었습니다
100vh 대신 100%를 사용해서 모바일에서도 잘 보일 수 있도록 했습니다
- global style 변경
- 100vh -> 100%

[#160] 모바일 높이 조정

---

packages/shared/src/style/global.css

콘텐츠를 망치는 scrollbar를 지웠습니다
- 스크롤바를 추가하면 스크롤바 크기인 16px이 padding으로 오른쪽에서 밀려나는 문제가 있었습니다
- 이것 저것 시도해 봤지만 스크롤바를 지우는 게 가장 쉬운 방법이었습니다
- 어떻게 하면 스크롤바가 필요 없는 곳에선 스크롤바가 안 뜨고 필요한 곳에서는 뜨게 할 수 있을까?

[#163] scrollbar 제거

---

packages/app/src/features/register/molecules/ProjectsInput/index.tsx
packages/shared/src/atoms/MonthPicker/index.tsx
packages/shared/src/molecules/MultiMonthPicker/index.stories.tsx
packages/shared/src/molecules/MultiMonthPicker/index.tsx
packages/shared/src/molecules/MultiMonthPicker/style.ts

- MultiMonthPicker에 진행중 checkbox를 추가했습니다
- MultiMonthPicker에 진행중 checkbox를 추가해 check되면 endDate 값이 null 되도록 했습니다
- check시 모달도 안 띄워지게 처리했습니다
- react hook form의 register에서 null을 허용 하도록 변경해야지 잘 동작해서 register 코드를 조금 수정했습니다

[#187] MultiMonthPicker 진행중 checkbox 추가

---

packages/app/src/api/CustomBaseQuery.ts
packages/app/src/api/rtkApi.ts
packages/app/src/features/auth/hook/useAuth.tsx
packages/app/src/features/auth/hook/useAutoReissue.tsx
packages/app/src/features/auth/lib/createSetCookie.ts
packages/app/src/features/auth/service/login.ts
packages/app/src/features/auth/service/reissue.ts
packages/app/src/features/global/hooks/useLocalStorage.tsx
packages/app/src/pages/_app.tsx
packages/app/src/pages/api/login.ts
packages/app/src/pages/api/reissue.ts

cookie를 사용하게 되면서 기존 토큰 재발급 로직을 수정했습니다
- 쿠키가 클라에 저장되지 않는 게 보이지 않아서 직접 쿠키를 넣어줬습니다. 로그인과 토큰 재발급 요청을 수정함
- 토큰 재발급을 api 요청할 때 진행하는 것이 아닌 setTimeout을 통해 시간이 지나면 하도록 변경했습니다

[#200] 토큰 재발급 로직 추가

---

packages/app/src/features/auth/hook/useLogout.tsx

로그아웃을 진행해도 header의 상태는 그대로인 문제가 발생했습니다
로그아웃 이후에 rtk query 상태를 초기화 하도록 만들었습니다

[#232] 로그아웃 문제 해결

---

packages/app/src/features/auth/hook/useAuth.tsx
packages/app/src/features/modal/hooks/useLoading.tsx
packages/app/src/features/register/hooks/useImageUpload.tsx
packages/app/src/features/register/hooks/useRegister.tsx
packages/app/src/features/student/hooks/useModifyProfile.tsx

submit 버튼을 연타할 경우 데이터가 두 번 날라갈 수 있는 문제가 있습니다
이를 해결하기 위해 페이지가 옮겨진 후에 로딩 페이지를 닫게 하도록 변경했습니다
- useLoading 훅에서 로딩 모달을 바로 닫지 않게 하다가 loadingClose를 실행하면 닫히도록 변경했습니다
- useLoading을 사용하는 hook들은 url을 변경한 후에 loadingClose를 실행하도록 변경했습니다
redirect를 useLoading 훅에서도 처리하면 좋을 것 같다는 생각이 들지만
귀찮기도 하고 잘 모르겠고 loadingWrap의 response 타입 관리도 귀찮아서 다음으로 미루도록 하겠습니다

[#237] 연속 요척을 막는 처리 추가

---

packages/app/src/features/student/hooks/useStudent.tsx

page1을 계속해서 가져오는 문제가 발생했습니다
때문에 학생 21명 이상만 있으면 진짜 평생 무한 스크롤이 가능해 지게 되었습니다
무한 스크롤 이후 page값을 카운트 하도록 변경했습니다

[#247] 무한 스크롤 오류 해결

---

packages/app/src/features/register/atoms/InputColumn/style.ts
packages/app/src/features/register/atoms/LinkMultiDoubleInput/index.tsx
packages/app/src/features/register/molecules/PrizeInputs/index.tsx
packages/app/src/features/register/molecules/ProfileInputs/index.tsx
packages/app/src/features/register/molecules/ProjectsInput/index.tsx
packages/app/src/features/register/molecules/SchoolInputs/index.tsx
packages/app/src/features/register/molecules/WorkingInputs/index.tsx
packages/shared/src/molecules/SearchInput/index.tsx

학생 정보 기입 부분에 기본 조건이 변경되었습니다
- projects.name 에 30자 제한을 추가했습니다
- projects.links.url에 5000자 제한을 추가했습니다
- projects.links.name 에 30자 제한을 추가했습니다
- projects.description에 1000자 제한을 추가했습니다
- projects.myActivity에 1000자 제한을 추가했습니다
- prizes.name에 40자 제한을 추가했습니다
- prizes.kind에 20자 제한을 추가했습니다
- techStacks에 1개 이상 제한을 풀었습니다
- gsmAuthenticationScore를 기존 3000점에서 9999점으로 변경했습니다
- techStacks의 각각의 기술들의 길이를 30자로 줄였습니다

[#245] 학생 정보 기입 폼 조건 수정

---

packages/app/src/features/auth/service/loggedInApi.ts
packages/app/src/features/server/services/accessService.ts
packages/app/src/pages/api/verify.ts

쿠키의 만료 날짜와 jwt의 만료 날짜가 같지 않은 문제가 발생했습니다
백엔드에 access 요청을 날릴 때 토큰의 날짜가 만료되었으면 자동으로 지워주도록 했습니다

[#260] 쿠키를 자동으로 지워주는 작업 추가

---

packages/app/src/api/serverApi.ts
packages/app/src/features/server/libs/checkTokenExpiration.ts
packages/app/src/features/server/libs/index.ts
packages/app/src/features/server/libs/withHandler.ts
packages/app/src/features/server/services/errors.ts
packages/app/src/features/server/services/index.ts
packages/app/src/features/server/services/loginService.ts
packages/app/src/features/server/services/logoutService.ts
packages/app/src/features/server/services/reissueService.ts
packages/app/src/features/server/services/studentDetailService.ts
packages/app/src/features/student/lib/findRole.ts
packages/app/src/pages/api/login.ts
packages/app/src/pages/api/logout.ts
packages/app/src/pages/api/reissue.ts
packages/app/src/pages/api/student/[studentId].ts
packages/app/src/pages/api/verify.ts

서버 로직을 리팩토링 하고
에러 핸들링을 추가했습니다
- withHandler를 만들어서 서버 api 부분에 적용시켰습니다
- withHandler를 통해 에러 핸들링을 편하게 했습니다

[#257] 서버 로직 리팩토링 및 에러 핸들링 추가

---

packages/app/src/features/student/hooks/useStudent.tsx
packages/app/src/features/student/molecules/StudentList/index.tsx
packages/app/src/features/student/stores/studentListSlice.ts
packages/app/src/features/student/stores/studentParamSlice.ts
packages/shared/src/atoms/Skeleton/index.tsx
packages/shared/src/atoms/StudentCard/style.ts

학생이 20명을 넘으면 skeleton ui가 꺼지지 않는 문제를 발견했습니다
- 어떻게 코드를 지우고 수정을 하다보니 해결이 되었습니다
- 정확히 뭐가 문제였는 지는 모르지만 알아 내면 적을 예정입니다
- 학생 리스트에서 맨 아래에 skeleton ui가 떠서 보일 때 다음 페이지 query를 날리 도록 수정했습니다

[#275] skeleton ui 버그 해결 및 로직 수정

---

packages/app/src/features/register/hooks/useMajorAutoComplete.tsx
packages/app/src/features/student/atoms/MajorListSection/index.tsx
packages/app/src/features/student/molecules/FilterModal/index.tsx
packages/shared/src/atoms/Checkbox/style.ts
packages/shared/src/atoms/Skeleton/index.tsx

분야를 입력할 수 있는 부분은 서버에서 가져오기 때문에
skeleton ui를 통해 분야 리스트를 가져오는 동안 띄우도록 했습니다
- skeleton ui 추가
- checkbox css 수정

[#278] filter 모달 skeleton ui 추가

---

packages/app/src/features/auth/hook/useLoggedIn.tsx
packages/app/src/features/register/services/PostTeacherRegisterService/index.tsx
packages/app/src/pages/register/teacher.tsx

+ 선생님 회원가입이 메인페이지 -> 선생님회원가입 -> 메인패이지 순으로 무한 페이지이동을 반복했습니다.
+ api의 주소가 잘못 입력되어 로그인의 기능을 하지 않았습니다.
Resolves: #303 
+ 메인페이지 이동을 방지했습니다.
+ api  주소를 수정했습니다.
> 구현 시에 고민이었던 점들 혹은 특정 부분에 대한 의도가 있었다면 PR 리뷰의 이해를 돕기 위해 서술해주세요!
>
> 또한 리뷰어에게 특정 부분에 대한 집중 혹은 코멘트 혹은 질문을 요청하는 경우에 작성하면 좋아요!
>
> e.g. 작업을 끝내야할 시간이 얼마 없어 확장성보다는 동작을 위주로 만들었어요! 감안하고 리뷰해주세요!
> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!

[#303] 회원가입 리렌더링 및 요청 문제 해결

---

packages/app/src/features/student/molecules/MyPageForm/index.tsx
packages/app/src/features/student/molecules/ProfileInputs/index.tsx
packages/shared/src/molecules/MultiDoubleInput/index.tsx
packages/shared/src/molecules/MultiInput/index.tsx

- 포트폴리오 입력이 필수 입력값이었음
- 자격증과 언어 영역 임베드가 하나 무조건 자동 생성됨.
Resolves: #{이슈번호}
- 포트폴이오 필수 여부를 false로 처리함
- 자격증과 언어 영역 Input useEffect 삭제

[#312] 마이페이지 수정 요구사항 반영

---

.github/workflows/SMS-app-CI.yml
.github/workflows/SMS-shared-CI.yml
package.json
packages/app/package.json
packages/app/src/features/auth/lib/setAuthCookies.ts
pnpm-lock.yaml

- POST 요청을 next server에 보내면 hot reloader가 죽고 브라우저와 nextjs 개발섭과의 통신이 끊어지는 문제를 발견했습니다
Resolves: #337
- nextjs 버전을 13.3.0에서 13.5.6으로 마이그레이션했습니다
- 추가로 타입 에러 때문에 cookie option 타입을 수정하는 작업을 진행했습니다
[참고 링크](https://github.com/vercel/next.js/pull/48039)

[#337] hot reloader가 끊기는 문제 해결

---

packages/app/src/features/student/queries/useStudentDetailQuery.tsx
packages/shared/src/atoms/StudentCard/index.tsx

- 학생 이름 변경 `변**` -> `변소금`
- 학생 detail 페이지 문제 해결
- 디테일 페이지의 학생 정보가 초기화 되지 않는 문제를 해결했습니다
Resolves: #357
- 학생 정보 조회 props 값 수정
- 리스트 페이지의 학생 이름 수정

[#357] 학생 리스트 페이지 버그 수정
