GSM-MSG/SMS-FrontEnd

- .github/workflows/SMS-CI.yml
> [#3] CI 추가

- packages/app/package.json
- packages/app/src/pages/_app.tsx
- packages/app/src/store/index.ts
- pnpm-lock.yaml
> [#18] redux toolkit 설정

- .github/workflows/SMS-app-CI.yml
- .github/workflows/SMS-shared-CI.yml
- packages/shared/src/index.ts
ci를 수정합니다
`pnpm build:shared` 추가
> [#20] ci 수정

- packages/shared/src/atoms/Button/index.stories.ts
- packages/shared/src/atoms/Button/index.tsx
- packages/shared/src/atoms/Button/type.ts
버튼을 추가합니다
> defalut : 파랑
> white : outline만 있는 거
```tsx
<Button theme="default | white" />
```
> [#28] 기본 버튼 추가

- packages/shared/src/atoms/Input/index.tsx
- packages/shared/src/atoms/Input/style.ts
Input의 자잘한 문제를 해결했습니다
- Input outline 안에서 선택을 해도 focus가 안되는 문제 해결
- 반응형을 위한 사이즈 조정
- form 태그 지우기
- hover시 커서 모양 바꾸기
> [#55] Input의 간단한 문제 해결

- packages/shared/src/atoms/DeleteButton/index.stories.ts
- packages/shared/src/atoms/DeleteButton/index.tsx
- packages/shared/src/atoms/DeleteButton/style.ts
- packages/shared/src/atoms/index.ts
삭제 버튼 요소를 추가합니다
```ts
import { DeleteButton } from '@sms/shared'
const Component = () => {
return (
<DeleteButton />
)
}
```
> [#57] 삭제 버튼 추가

- packages/shared/.storybook/preview.js
- packages/shared/src/assets/svg/Person.tsx
- packages/shared/src/atoms/StudentCard/index.stories.tsx
- packages/shared/src/atoms/StudentCard/index.tsx
- packages/shared/src/atoms/StudentCard/style.ts
- packages/shared/src/style/devStyle.css
학생 소개 카드를 만들었습니다
기술 스택 부분의 ... 처리는 아직 완성되지 않았습니다
> [#82] 학생 소개 카드 만들기

- packages/app/src/api/axiosApi.ts
- packages/app/src/api/index.ts
- packages/app/src/api/rtkApi.ts
- packages/app/src/api/serverApi.ts
- packages/app/src/features/auth/service/login.ts
rtk query 설정을 추가했습니다
- rtkApi 추가
- `serverApi` -> `axiosApi`
기존 serverApi를 axiosApi로 변경했습니다
> [#84] rtk query 설정 추가

- packages/app/src/store/index.ts
rtk를 store에 등록하는 걸 빼먹어서 추가했습니다
store의 middleware에 추가했습니다
> [#84] rtk query 빼먹은 설정 추가

- packages/app/src/api/axiosApi.ts
- packages/app/src/features/auth/service/reissue.ts
- packages/app/src/lib/TokenManager.ts
- packages/app/src/lib/needsTokenRefresh.ts
토큰 로테이션 로직 문제점 수정
- 조건문 수정
- 토큰 재발급이 필요 없을 때 토큰을 아예 넣지 못하게 변경
- baseUrl 추가
- 실수 수정
> [#91] 로그인 처리 문제점 수정

- packages/app/src/features/auth/hook/useLoggedIn.tsx
- packages/app/src/features/auth/hook/useLogout.tsx
- packages/app/src/features/auth/hook/useWithdraw.tsx
- packages/app/src/features/auth/service/loggedInApi.ts
- packages/app/src/features/auth/service/logout.ts
- packages/app/src/features/auth/service/withdraw.ts
- packages/app/src/features/student/hooks/useStudentDetail.tsx
- packages/app/src/features/student/templates/StudentsTemplate/index.tsx
- packages/app/src/lib/TokenManager.ts
- packages/app/src/pages/index.tsx
- packages/shared/src/molecules/Header/index.stories.tsx
- packages/shared/src/molecules/Header/index.tsx
- packages/shared/src/molecules/Header/style.ts
Header 컴포넌트에 있는 문제 해결 및 기능 추가를 했습니다
- Header에 로그아웃, 회원 탈퇴 기능을 추가합니다
- Header가 상단에 고정되도록 수정합니다
- 로그인이 되어있지 않은 상태에서 프로필을 누르면 로그인 페이지로 redirect됩니다
- TokenManager에 토큰이 없으면 요청을 못 날리게 했는데 이걸 이제 풀었음
> [#102] Header 문제 해결

- packages/shared/src/molecules/MultiDoubleInput/style.ts
- packages/shared/src/molecules/MultiInput/style.ts
아래와 같은 컴포넌트들에 스타일 문제가 있었습니다
- SearchInput
- MultiInput
- MultiDoubleInput
각각의 컴포넌트들에게 gap을 줘서 스타일을 수정했습니다
> [#106] input에서 파생된 컴포넌트 스타일을 수정합니다

- packages/shared/src/atoms/StudentCard/index.stories.tsx
- packages/shared/src/atoms/StudentCard/index.tsx
- packages/shared/src/atoms/StudentCard/style.ts
학생 정보를 간단하게 보여주는 카드에 반응형을 추가했습니다
> [#114] 학생 카드 반응형

- package.json
package.json에 배포 script를 추가했습니다
> [#117] 배포 관련 스크립트 추가

- packages/app/src/data/StudentDetailTestData.ts
- packages/app/src/features/student/molecules/StudentDetail/index.tsx
- packages/app/src/types/StudentDetail.d.ts
학생 디테일에서 기술 스택이 보이지 않는 문제가 있어서 수정했습니다
- `techStacks` -> `techStack`
> [#135] 학생 디테일 문제 해결

- packages/app/src/components/SEO/index.tsx
- packages/app/src/pages/login.tsx
- packages/app/src/pages/register.tsx
twitter card에서 title이 뜨지 않는 문제가 발생했습니다
- SEO 컴포넌트에 title 부분을 수정했습니다
- register 페이지에도 SEO 컴포넌트를 추가했습니다
- 페이지 title을 한글로 변경했습니다
> [#136] twitter card title 문제 해결

- packages/app/package.json
- packages/app/src/components/Loading/index.tsx
- packages/app/src/components/Loading/style.ts
- packages/app/src/components/index.ts
- packages/app/src/features/auth/hook/useAuth.tsx
- packages/app/src/pages/_document.tsx
- packages/app/src/templates/LoginTemplate/index.tsx
- pnpm-lock.yaml
로그인 이후에 띄울 로딩 페이지를 추가했습니다
- loading 컴포넌트와 portal 추가
- 로그인 이후 isLoading을 추가하고 isLoading값이 활성화 되면 loading 컴포넌트가 활성화 되도록 설정
- react-lottie 라이브러리를 추가했습니다
> [#139] 로딩 페이지 추가

- packages/app/src/features/register/molecules/ProfileInputs/index.tsx
- packages/shared/src/atoms/Input/index.tsx
- packages/shared/src/atoms/Input/style.ts
- packages/shared/src/atoms/Input/type.ts
- packages/shared/src/molecules/SearchInput/index.tsx
SearchInput 컴포넌트의 성능을 개선했습니다
- SearchInput을 사용하는 곳에서 limit 값을 표시해 줬습니다
- disable 디자인을 수정했습니다
- 엔터를 입력하면 첫 번째 autocomplete가 선택되는 기능을 추가했습니다
- 똑같은 단어는 추가가 안되도록 막았습니다
> [#141] searchInput 성능 개선하기

- packages/shared/src/atoms/Input/index.tsx
- packages/shared/src/molecules/MultiRangeSlider/index.stories.ts
- packages/shared/src/molecules/MultiRangeSlider/index.tsx
- packages/shared/src/molecules/MultiRangeSlider/style.ts
최대값과 최소값을 한 번에 입력 받을 수 있는 MultiRangeSlider 컴포넌트를 추가했습니다
- MultiRangeSlider 구현하기
https://github.com/GSM-MSG/SMS-FrontEnd/assets/57276315/4ba28de5-8726-4be2-82f2-cc5cc226750c
> [#140] MultiRangeSlider 컴포넌트 추가

- packages/shared/src/molecules/MultiRangeSlider/index.stories.ts
- packages/shared/src/molecules/MultiRangeSlider/index.tsx
multiRangeSlider에 defaultValue를 추가했습니다
- 각각 min, max 따로 defaultValue를 입력받을 수 있게 했습니다
- min값을 담당하는 input과 max를 담당하는 input의 간격의 최소 값을 1로 했습니다
> [#148] multiRangeSlider default value 추가

- packages/shared/src/molecules/SearchInput/index.stories.tsx
- packages/shared/src/molecules/SearchInput/index.tsx
searchInput에 defaultValue 기능을 추가했습니다
- defaultValue 기능 추가
- 내부 stacks 타입을 string에서 string[] 로 변경
- 엔터시 stack 추가 메커니즘 변경
> [#151] searchInput defaultValue 기능 추가

- packages/app/src/features/student/molecules/FilterModal/index.tsx
- packages/shared/src/atoms/Input/index.tsx
- packages/shared/src/atoms/Input/style.ts
- packages/shared/src/molecules/MultiRangeSlider/index.tsx
- packages/shared/src/molecules/MultiRangeSlider/style.ts
- multiRangeSlider에 label을 달 수 있게 했습니다
- filter에 submit button 문구를 변경했습니다
> [#165] filter button 수정 및 multiRangeSlider label 추가

- packages/shared/src/atoms/DeleteButton/style.ts
- packages/shared/src/molecules/DoubleInput/index.stories.tsx
- packages/shared/src/molecules/DoubleInput/index.tsx
- packages/shared/src/molecules/DoubleInput/style.ts
기존 MultiDoubleInput은 특정 부분에서만 사용할 수 있도록 퍼블리싱 되었지만
이번에는 여러 곳에서 사용될 수 있도록 수정했습니다
- DeleteButton 수정
- DoubleInput 추가
MultiDoubleInput은 레거시로 남겨두고 나중에 언어 점수 입력 부분이 수정되면 같이 지우는 걸로 하겠습니다
> [#172] DoubleInput 추가

- packages/shared/src/atoms/DateInput/index.stories.ts
- packages/shared/src/atoms/DateInput/index.tsx
- packages/shared/src/atoms/DateInput/style.ts
- packages/shared/src/molecules/MultiDateInput/index.stories.tsx
- packages/shared/src/molecules/MultiDateInput/index.tsx
MultiDateInput이 react hook form 을 지원하도록 변경했습니다
- MultiDateInput 수정
- DateInput, forwardRef 에러 해결 및 에러 메시지를 띄울 수 있는 부분 추가
- MultiDateInput도 에러 메시지를 띄우도록 수정
> [#174] MultiDateInput react hook form 지원

- packages/app/src/features/modal/hooks/index.ts
- packages/app/src/features/modal/hooks/useModal.tsx
- packages/app/src/features/modal/portals/ModalPortal/index.tsx
- packages/app/src/features/modal/portals/ModalPortal/style.ts
- packages/app/src/features/modal/portals/index.ts
- packages/app/src/features/modal/providers/ModalProvider.tsx
- packages/app/src/features/modal/providers/index.ts
- packages/app/src/features/student/molecules/FilterModal/index.tsx
- packages/app/src/features/student/templates/StudentsTemplate/index.tsx
- packages/app/src/pages/_app.tsx
- packages/app/src/store/modalSlice.ts
기존 모달 기능은 새로운 모달을 추가하기가 매우 불편해서
비교적 확장이 쉬운 기능으로 변경했습니다
- 기존 모달 기능은 deprecated 시킴
- 새로운 모달 기능을 추가함
- filter에 새로운 모달 기능을 적용했음
학생 디테일은 디자인이 바뀌어서 한 번 갈아 엎을 예정이라 만지지 않았습니다
때문에 기존 모달 기능을 지우지는 않았습니다
> [#179] 모달 기능 수정

- packages/app/src/features/auth/lib/clearSetCookie.ts
- packages/app/src/features/auth/service/logout.ts
- packages/app/src/pages/api/logout.ts
로그아웃 이후 쿠키가 지워지지 않는 문제가 발생했습니다
쿠키를 지우기 위해 로그아웃 api를 만들어서 쿠키를 지워줬습니다
> [#202] 로그아웃 문제

- packages/app/package.json
- packages/app/src/features/student/hooks/useStudentDetail.tsx
- packages/app/src/features/student/molecules/StudentDetail/index.tsx
- packages/app/src/features/student/service/studentApi/index.ts
- packages/app/src/pages/api/student/[studentId].ts
- pnpm-lock.yaml
학생 디테일 요청에서 선생님, 학생, 외부인을 구분해서 api를 다르게 요청 했어야 하는 번거로움이 있었다
- 이걸 next api를 만들어서 쿠키를 읽고 권한을 구분하는 방식으로 변경함
> [#198] 학생 디테일 api 수정

- packages/app/src/features/auth/lib/clearSetCookie.ts
- packages/app/src/features/auth/lib/createSetCookie.ts
쿠키값 설정을 개발섭을 기준으로 만들어 버려서 쿠키가 저장되지 않는 문제가 발생했습니다
- 쿠키를 생성하는 로직과 수정하는 로직에 domain값이 유동적으로 바뀌도록 변경했습니다
> [#206] 배포시 로그인이 안되는 문제 해결

- packages/app/src/features/register/data/WorkType.ts
희망 고용 형태의 enum 값이 올바르지 않아서 생기는 문제를 해결했습니다
CONSTRACT -> CONTRACT
> [#217] 희망 고용 형태 문제 해결

- packages/app/src/features/student/atoms/ProfileDetail/index.tsx
- packages/app/src/features/student/molecules/StudentDetail/index.tsx
- packages/app/src/features/student/types/StudentType.ts
- packages/app/src/types/StudentDetail.d.ts
- packages/shared/src/atoms/StudentCard/index.stories.tsx
- packages/shared/src/atoms/StudentCard/index.tsx
- packages/shared/src/atoms/StudentCard/style.ts
techStack을 전에 사용 했지만 techStacks로 통일을 하면서 여기도 수정을 했습니다
- 메인 페이지 techStacks 수정
- 학생 디테일 페이지 techStacks 수정
> [#212] 기술 스택 문제 해결

- packages/app/src/features/auth/hook/useLogout.tsx
- packages/app/src/features/auth/hook/useWithdraw.tsx
- packages/app/src/features/modal/hooks/usePortal.tsx
- packages/app/src/features/modal/portals/BlurPortal/index.tsx
- packages/app/src/features/student/hooks/useModifyProfile.tsx
- packages/app/src/features/student/hooks/useStudent.tsx
- packages/app/src/features/student/hooks/useStudentsFilter.tsx
- packages/app/src/features/student/lib/toQueryString.tsx
- packages/app/src/features/student/molecules/StudentList/index.tsx
- packages/app/src/features/student/service/studentListApi.ts
- packages/app/src/features/student/templates/StudentsTemplate/index.tsx
- packages/app/src/pages/index.tsx
- packages/app/src/pages/student/[studentId].tsx
메인 페이지를 SSR로 렌더링 하도록 변경했습니다
- SSR 렌더링으로 수정
- filter 문제 해결
- 로그인, 로그아웃, 정보 수정 후에 학생 리스트를 재요청하는 로직을 지웠습니다
> [#222] 메인 페이지 SSR

- packages/app/src/features/student/hooks/useStudent.tsx
- packages/app/src/features/student/service/studentListApi.ts
- packages/app/src/pages/index.tsx
메인 페이지에서 SSR로 학생 리스트를 요청할 때 쿼리를 잘 못 보내서 에러가 발생했습니다
token값이 null 일 때만 클라에서 보내는 걸로 인식하게 만들었습니다
> [#225] 메인 페이지 에러 해결

- packages/app/package.json
- packages/app/src/api/axiosApi.ts
- packages/app/src/features/auth/hook/useAuth.tsx
- packages/app/src/features/auth/hook/useAutoReissue.tsx
- packages/app/src/features/global/hooks/useLocalStorage.tsx
- pnpm-lock.yaml
가끔씩 노트북을 덮고 있다던가 오랫동안 사이트에 접속하지 않으면
토큰이 꼬이는 현상을 발견했습니다
- 재요청 기능 추가
- 토큰 재발급 기능 수정
- 온라인 이벤트와 window 포커스 이벤트를 감지하는 기능을 추가했습니다
아직 완벽하게 동작 할지는 모르겠습니다
어떤 상황에 문제가 발생할지 몰라서...
> [#229] 토큰 재발급 문제 해결

- packages/app/src/features/register/hooks/useRegister.tsx
- packages/app/src/features/register/molecules/CertificateInputs/index.tsx
- packages/app/src/features/register/molecules/ProfileInputs/index.tsx
- packages/app/src/features/register/molecules/ProjectsInput/index.tsx
- packages/app/src/features/register/molecules/WorkingInputs/index.tsx
- packages/app/src/features/register/organisms/RegisterForm/style.ts
- packages/app/src/features/student/hooks/useStudentsFilter.tsx
- packages/app/src/features/student/molecules/FilterModal/index.tsx
- packages/app/src/features/student/molecules/MyPageForm/style.ts
- packages/app/src/features/student/templates/StudentsTemplate/index.tsx
- packages/shared/src/atoms/Tag/index.tsx
- packages/shared/src/molecules/MultiDoubleInput/index.tsx
- packages/shared/src/molecules/MultiInput/index.tsx
- packages/shared/src/molecules/SearchInput/index.stories.tsx
- packages/shared/src/molecules/SearchInput/index.tsx
정보 입력 페이지에 있는 오류들을 몇가지 수정했습니다
- 자격증과 외국어를 입력하는 input을 전부 지울 수 있게 하는 기능을 추가했습니다
-  자격증과 외국어가 자동 생성되지 않는 문제를 해결했습니다
- SearchInput 로직을 개선했습니다
이슈에 작서했던 SearchInput이 error를 띄우지 않는 문제는 나중에 해결하기로 결정했습니다
> [#228] 정보 입력 페이지 기능 수정

- packages/app/src/features/auth/lib/clearSetCookie.ts
- packages/app/src/features/auth/lib/createSetCookie.ts
쿠키가 지워지지 않는 문제가 발생했습니다
이 문제가 맞는 지는 모르겠지만 부족한 부분이 same site 옵션 밖에 없어서 일단 추가해 보기로 했습니다
> [#233] same site 옵션 추가

- packages/app/src/features/auth/lib/createSetCookie.ts
쿠키가 지워지지 않는 문제가 발생해서 만료 날짜 설정 방식을 바꾸는 방법을 선택했습니다
expires에서 max-age로 변경했습니다
> [#233] 쿠키 만료 날짜 설정 바꾸기

- packages/app/next.config.js
- packages/app/package.json
- packages/app/src/features/global/Header/index.tsx
- packages/app/src/features/global/Header/style.ts
- packages/app/src/features/modal/hooks/useModal.tsx
- packages/app/src/features/modal/hooks/usePortal.tsx
- packages/app/src/features/student/atoms/ProfileDetail/index.tsx
- packages/app/src/features/student/atoms/ProfileDetail/style.ts
- packages/app/src/features/student/atoms/ProjectDetail/index.tsx
- packages/app/src/features/student/atoms/ProjectDetail/style.ts
- packages/shared/src/atoms/StudentCard/index.tsx
- packages/shared/src/atoms/StudentCard/style.ts
- pnpm-lock.yaml
이미지 로딩 속도가 너무 느려서 렌더링 최적화 작업을 진행했습니다
- 일번 img 태그들을 Nextjs의 Image 태그로 변경했습니다
- sharp 라이브러리를 추가했습니다
- 이미지 사이즈 조정을 위해 스타일을 수정했습니다
- 디테일 페이지에서 메인 페이지로 돌아올때 맨 위로 자동 스크롤 되는 문제를 해결했습니다
> [#199] 이미지 렌더링 최적화

- packages/app/next.config.js
- packages/app/src/features/auth/errors.ts
- packages/app/src/features/register/services/errors.ts
- packages/app/src/features/student/service/errors.ts
- packages/app/src/features/student/service/profileService.ts
- packages/app/src/features/student/service/studentDetailApi.ts
- packages/app/src/features/student/service/studentListApi.ts
- packages/app/src/lib/env.ts
- packages/app/src/pages/api/login.ts
- packages/app/src/pages/api/logout.ts
- packages/app/src/pages/api/reissue.ts
server url이 담겨있는 `NEXT_PUBLIC_SERVER_URL` 은 클라이언트에서 사용할 필요가 없다고 판단이 되었습니다
next에서는 `NEXT_PUBLIC_` prefix를 환경 변수 이름 앞에적어주면 클라이언트 사이드에서 사용할 수 있다고 합니다
때문에  `NEXT_PUBLIC_`를 지워주는 작업을 진행했습니다
- 환경변수 변경
-   `NEXT_PUBLIC_`이 없는 환경 변수는 env.ts 파일에서 관리하기가 어려울 것 같아서 직접 작성하게 만들었습니다
> [#239] 환경 변수 수정

- packages/app/src/features/student/atoms/ProfileDetail/index.tsx
- packages/app/src/features/student/atoms/StudentInfo/index.tsx
- packages/app/src/features/student/molecules/StudentDetail/index.tsx
디테일 페이지에 잘 못 입력된 부분을 수정했습니다
- 학과를 항상 소프트웨어 개발과로 보이게 만들어서 수정했습니다
- 희망 연봉이 0원이면 상관없음 으로 띄우게 수정했습니다
> [#242] 디테일에 잘못 된 부분 수정

- packages/app/src/features/auth/lib/createSetCookie.ts
토큰 만료 값이 이상한 문제 해결했습니다
max age값은 초 단위이고 new Date().getTime() 은 밀리초 단위기 때문에 1000을 나누어서 값을 맞추어 주었습니다
> [#250] 토큰 만료값 수정

- packages/app/src/features/auth/lib/createSetCookie.ts
vercel의 time zone이 외국으로 되어 있어서 시간 계산이 이상했던 것 같습니다
date 객체를 생성 할 때 time zone 값을 설정하는 코드를 추가했습니다
> [#250] 쿠키 만료 날짜 수정

- packages/app/src/features/auth/lib/createSetCookie.ts
기존 UTC 시간을 반환 하는 것과는 달리 max-age로 변경하고 초 단위로 반환하게 변경했습니다
> [#250] 쿠키 날짜 계산 수정

- packages/app/src/features/auth/hook/useLogout.tsx
- packages/app/src/features/auth/lib/createSetCookie.ts
- packages/app/src/pages/api/login.ts
- packages/app/src/pages/api/reissue.ts
쿠키 날짜를 직접 넣어주려고 했지만 배포 서버에서 날짜 계산에 문제가 있어서
서버에서 주는 Set-Cookie를 변조하는 방식으로 변경했습니다
- 로그아웃에서 로컬스토리지 지우기
- createSetCookie 함수 수정
> [#250] 쿠키 설정 값 수정

- packages/app/src/features/student/atoms/StudentInfo/index.tsx
> [#259] 연락할 이메일 추가

- packages/app/src/features/student/hooks/useStudentsFilter.tsx
- packages/app/src/features/student/molecules/FilterModal/index.tsx
- packages/app/src/lib/ParamsFilter.ts
- packages/app/src/types/StudentParam.d.ts
- packages/shared/src/molecules/SearchInput/index.tsx
필터에서 발생하는 자잘한 버그들을 수정했습니다
- 필터에 있는 세부스택 직접 입력 기능은 필요없으므로 지웠습니다
- 분야 부분에 오타를 수정하고 기타 부분을 추가했습니다
- 동작하지 않는 오름차순 문제를 해결했습니다
> [#258, #252, #251] 필터 문제 해결

- .github/workflows/SMS-app-CI.yml
- .github/workflows/SMS-shared-CI.yml
- package.json
- packages/app/package.json
- pnpm-lock.yaml
react-query, zod, @hookform/resolvers 의존성 추가
더 편한 개발을 위해 의존성을 추가했습니다
Resolves: #295
- zod, react-query, @hookform/resolvers 의존성 추가
- pnpm 버전을 `8.2.0`에서 `9.1.2`으로 업데이트 했습니다
> [#295] 의존성 추가

- packages/app/src/features/global/Header/index.tsx
인증제 버튼을 제한해야합니다.
인증제 dropdownItem을 주석 처리합니다.
> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!
> [#304] SMS 인증제 바로가기 버튼 제한

- .editorconfig
- packages/app/src/features/global/Header/index.tsx
- packages/app/src/features/student/molecules/MyPageForm/index.tsx
> insert_final_newline 옵션이 잘못 설정되어 있어서 prettier와 충돌을 일으키는 문제가 있었습니다
Resolves: #320
- insert_final_newline 옵션을 true로 변경했습니다
- 잘못 적용된 코드들을 바로잡았습니다
> editorconfig 설정 수정

- packages/shared/src/molecules/CertificationForm/Field.tsx
- packages/shared/src/molecules/CertificationForm/index.stories.tsx
- packages/shared/src/molecules/CertificationForm/style.ts
> 한 field에 input이 여러개일 때 ui를 대응하지 못해 찌그러지는 문제가 있습니다
Resolves: #323
> input이 여러개일 때 대응하는 코드를 작성했습니다
> [#323] 다중 input 문제 해결

- packages/shared/src/atoms/SegmentedControl/Option.tsx
- packages/shared/src/atoms/SegmentedControl/Root.tsx
- packages/shared/src/atoms/SegmentedControl/index.stories.tsx
- packages/shared/src/atoms/SegmentedControl/index.tsx
- packages/shared/src/atoms/SegmentedControl/style.ts
- 현재 SegmentedControl 컴포넌트는 boolean 밖에 컨트롤을 하지 못해 현재 요구사항에 충족하지 못합니다
- 때문에 여러 값을 control 할 수 있게 수정을 진행했습니다
Resolves: #325
- radio 를 통해서 SegmentedControl 값을 컨트롤 하도록 수정했습니다
- radio 로 값을 조종하다보니 아쉽게도 애니메이션이 빠지게 되었습니다
- 추후에 애니메이션을 추가하도록 합시다
> [#325] SegmentedControl 컴포넌트 수정

- packages/shared/src/atoms/FileInput/index.stories.tsx
- packages/shared/src/atoms/FileInput/index.tsx
- packages/shared/src/atoms/FileInput/style.ts
- 파일입력을 위한 컴포넌트를 추가했습니다
Resolves: #327
- 참고로 ui만 구현했습니다
- 때문에 react hook form과 같이 사용하려면 가공이 한 번더 필요합니다
> [#327] 파일 입력 컴포넌트 추가

- packages/shared/src/atoms/FileInput/index.stories.tsx
- packages/shared/src/atoms/FileInput/index.tsx
- packages/shared/src/atoms/FileInput/style.ts
- hover, focus 스타일이 디자인과 맞지 않는 문제가 있습니다
- placeholder가 없습니다
- 파일 업로드에 실패해도 input에 파일 이름이 뜹니다
Resolves: #331
- FileInput 스타일 수정
- placeholder props 추가
- 파일 업로드 로직 수정 (storybook 참고)
> [#331] FileInput 문제 해결

- packages/app/package.json
- packages/app/src/features/dialog/molecules/DialogProvider.tsx
- packages/app/src/features/modal/providers/ModalProvider.tsx
- packages/app/src/features/student/queries/useStudentListQuery.tsx
- packages/app/src/features/toast/components/ToastContainer/index.tsx
- packages/app/src/pages/_app.tsx
- packages/app/src/store/index.ts
- pnpm-lock.yaml
- next-redux-wrapper를 제거했습니다
- [redux 최적화 오류](https://redux.js.org/usage/deriving-data-selectors#optimizing-selectors-with-memoization)를 해결했습니다
Resolves: #335
> redux 설정 수정

- packages/app/src/features/auth/queries/useLoggedInQuery.tsx
- packages/app/src/features/auth/service/loggedInService.ts
- packages/app/src/features/student/atoms/FileUpload/index.tsx
- packages/app/src/features/student/atoms/NumberInput/index.tsx
- packages/app/src/features/student/atoms/SelectInput/index.tsx
- packages/app/src/features/student/atoms/TextInput/index.tsx
- packages/app/src/features/student/dtos/res/AuthenticationFromResDto.ts
- packages/app/src/features/student/service/fetchAuthenticationForm.ts
- 인증제 페이지에 접근이 안되는 문제를 해결했습니다
Resolves: #353
> [#353] 인증제 페이지 접근 문제 해결

- packages/app/src/features/global/Header/index.tsx
- packages/app/src/features/student/hooks/useStudentAuthenticationRedirect.tsx
- packages/app/src/features/teacher/organisms/GradeScoreForm/index.tsx
- packages/app/src/features/teacher/queries/useAuthenticationStudentListMutation.tsx
학생 점수 관리 페이지에 부족한 부분이 있어서 수정했습니다
Resolves: #355
- submit 후에 리스트 페이지로 redirect 추가
- header에 학생 리스트 링크 추가
> [#355] 인증제 점수 입력 버그 해결

- packages/app/src/features/student/atoms/StudentInfo/index.tsx
- 값의 유무 판단을 숫자로 해서 생긴 문제입니다
Resolves: #359
- 숫자를 boolean으로 바꿔서 판단하게 변경했습니다
> [#359] 학생 디테일 모달에 0이 띄워지는 문제 해결

- packages/app/src/pages/api/server/[...params].ts
- packages/app/src/pages/api/server/file/image.ts
- packages/app/src/pages/api/server/file/index.ts
- packages/app/src/pages/api/server/student/pdf.ts
> 서버로 api를 보내도 다른 프론트 url로 날라가는 문제를 해결했습니다
Resolves: #362
> Route API에서 header값에 host를 수정했습니다
> [#362] api host 문제 해결
